apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: wgqlg-withretrieval-schemasplit-train-80-v4
spec:
  # image: substratusai/model-trainer-huggingface
  build:
    git:
      url: https://github.com/substratusai/images
      branch: update-hyper-params
      path: model-trainer-huggingface
  model:
    name: llama-2-7b
  env:
    HUGGING_FACE_HUB_TOKEN: ${{ secrets.ai.HUGGING_FACE_HUB_TOKEN }}
  params:
    # See HuggingFace transformers.TrainingArguments for all parameters
    # https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments
    num_train_epochs: 3
    dataset_urls: https://huggingface.co/datasets/weaviate/WithRetrieval-SchemaSplit-Train-80/resolve/main/WithRetrieval-Random-Train-80.json
    push_to_hub: substratusai/wgql-WithRetrieval-SchemaSplit-Train-80
    save_steps: 50
    logging_steps: 50
    warmup_steps: 100
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    target_modules: "q_proj, up_proj, o_proj, k_proj, down_proj, gate_proj, v_proj"
    modules_to_save: "embed_tokens, lm_head"
    prompt_template: |
      ## Instruction
      Your task is to write GraphQL for the Natural Language Query provided. Use the provided API reference and Schema to generate the GraphQL. The GraphQL should be valid for Weaviate.

      Only use the API reference to understand the syntax of the request.

      ## Natural Language Query
      {nlcommand}

      ## Schema
      {schema}

      ## API reference
      {apiRef}

      ## Answer
      {output}
    inference_prompt_template: |
      ## Instruction
      Your task is to write GraphQL for the Natural Language Query provided. Use the provided API reference and Schema to generate the GraphQL. The GraphQL should be valid for Weaviate.

      Only use the API reference to understand the syntax of the request.

      ## Natural Language Query
      {nlcommand}

      ## Schema
      {schema}

      ## API reference
      {apiRef}

      ## Answer
      ```graphql
  resources:
    gpu:
      count: 4
      type: nvidia-l4
