apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: eval-withretrieval-schemasplit-train-40
spec:
  env:
    HUGGING_FACE_HUB_TOKEN: "${{ secrets.ai.HUGGING_FACE_HUB_TOKEN }}"
      #  model:
      #    name: wgqlg-withretrieval-schemasplit-train-80
  params:
    hf_dataset: weaviate/WithoutRetrieval-SchemaSplit-Test-40
    push_to_hub: substratusai/wgql-WithRetrieval-SchemaSplit-Train-40
    prompt_template: |
      ## Instruction
      Your task is to write GraphQL for the Natural Language Query provided. Use the provided API reference and Schema to generate the GraphQL. The GraphQL should be valid for Weaviate.

      Only use the API reference to understand the syntax of the request.

      ## Natural Language Query
      {nlcommand}

      ## Schema
      {schema}

      ## API reference
      {apiRef}

      ## Answer
      ```graphql

  resources:
    gpu:
      type: nvidia-l4
      count: 1
